This directory contains sequence data generated by the 1000 Genomes Project, and alignment data of the reads to GRCh38.  
Subsequent analysis results such as variant call sets will be in this directory when they become available. 

##Sequence Data##

Moving forward we are aligning the raw sequence data unfiltered, as such we no long rehost the fastq files but instead our
sequenceindex files point you to the FTP url for the fastq files on ENA servers 

The data in the sequence index are categorised into 3 analysis groups (column 26) based on the library strategy used:

low coverage - Low coverage whole genome sequencing
exome - Whole exome sequencing 
high coverage - PCR-free high coverage whole genome sequencing

When align to GRCh38,  data from the three analysis groups were aligned independently, producing three sets of CRAM files.

Some of the runs have a withdrawn flag (column 21); these runs were not included in subsequent analysis. 
Column 22 indicates the reason why a run is withdrawn.  Below are the possible reasons:

SUPPRESSED IN ARCHIVE - runs were withdrawn by submitters so the fastq file is no longer available from ENA/SRA
TOO_SHORT - alll reads in a  whole genome sequencing run are shorter than 70bp or in a exome run shorter than 68bp
NOT_ILLUMINA - a run generated on a platform that is not Illumina.  For data consistency, we only include data produced on the Illumina platform for subsequent analysis. 

## Alignment Data ##

The sequence data described by the sequence index file (1000genomes.sequence.index) were aligned to GRCh38 using ALT-aware bwa-mem. Please see details of the alignment process in README.1000genomes.GRCh38DH.alignment.  Sample level CRAMs were produced; the CRAM files and ancillary files are listed in alignment index files in this directory.

